# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:3.6.18
    hostname: mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=hBbeOfpFLfFT5ZO
    networks:
      - compute
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    expose:
      - "27017"

  db:
    image: mariadb:5.5
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - compute
    volumes:
      - ./mysql.d:/etc/mysql/mariadb.conf.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
  #xdmod:
  #  image: moc-xdmod
  #  restart: always
  #  command: [ /usr/sbin/httpd -DFOREGROUND ]
  #  networks:
  #    - compute
  #  expose:
  #    - "4443"
  #    - "443"
  #    - "22"
  #  volumes:
  #    - ~/.config/openstack/clouds.yaml:/root/.config/openstack/cloouds.yaml
  #  ports:
  #    - "127.0.0.1:8080:80"
  #    - "127.0.0.1:4443:443"
  #  depends_on:
  #    - mongodb
  #    - mariadb

networks:
  compute:
