apiVersion: v1
kind: PersistentVolume
metadata:
  name: xdmod-data-pv
  labels:
    type: local
spec:
  storageClassName: xdmod-src
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/host/xdmod_data"
