apiVersion: v1
kind: PersistentVolume
metadata:
  name: xdmod-src-pv
  labels:
    type: local
spec:
  storageClassName: xdmod-src
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host/xdmod_src"
