kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: xdmod
namespace: xdmod

resources:
  - ../../xdmod-build
  - ../../kube-base

patchesStrategicMerge:
  - patches/cj-xdmod-openstack-shred.yaml
  - patches/cj-xdmod-ingestor.yaml
  - patches/cj-xdmod-hierarchy.yaml
  - patches/deployment-xdmod.yaml
