apiVersion: batch/v1
kind: CronJob
metadata:
  name: xdmod-ingestor
spec:
  schedule: "0 14 */1 * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          initContainers:
            - name: download-config
              image: xdmod-openstack
              imagePullPolicy: IfNotPresent
              command:
                - "/app/xdmod-get-config.sh"
              volumeMounts:
                - name: vol-xdmod-conf
                  mountPath: /etc/xdmod
                - name: vol-clouds-yaml
                  mountPath: /etc/openstack
                - name: vol-xdmod-init
                  mountPath: /mnt/xdmod_init
                - name: vol-var-log-xdmod
                  mountPath: /var/log/xdmod
          containers:
            - name: moc-xdmod
              image: moc-xdmod
              imagePullPolicy: IfNotPresent
              command:
                - "/usr/bin/xdmod-ingestor"
              volumeMounts:
                - name: vol-xdmod-conf
                  mountPath: /etc/xdmod
                - name: vol-clouds-yaml
                  mountPath: /etc/openstack
                - name: vol-xdmod-init
                  mountPath: /mnt/xdmod_init
                - name: vol-var-log-xdmod
                  mountPath: /var/log/xdmod
          restartPolicy: Never
          volumes:
            - name: vol-xdmod-init
              configMap:
                items:
                  - key: xdmod_init.json
                    path: xdmod_init.json
                name: cm-xdmod-init-json
            - name: vol-xdmod-conf
              emptyDir: {}
            - name: vol-clouds-yaml
              emptyDir: {}
            - name: vol-var-log-xdmod
              emptyDir: {}
