apiVersion: batch/v1
kind: CronJob
metadata:
  name: xdmod-openshift-prod-job
spec:
  schedule: "0 13 */1 * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          initContainers:
            - name: download-config
              image: image-registry.openshift-image-registry.svc:5000/xdmod/xdmod-openstack:latest
              imagePullPolicy: IfNotPresent
              command:
                - "/app/xdmod-get-config.sh"
              volumeMounts:
                - name: vol-xdmod-conf
                  mountPath: /etc/xdmod
                - name: vol-clouds-yaml
                  mountPath: /etc/openstack
                - name: vol-xdmod-init
                  mountPath: /mnt/xdmod_init
                - name: vol-var-log-xdmod
                  mountPath: /var/log/xdmod
          containers:
            - name: xdmod-openshift-prod-job
              image: image-registry.openshift-image-registry.svc:5000/xdmod/moc-xdmod:latest
              imagePullPolicy: Always
              env:
                - name: OPENSHIFT_PROMETHEUS_URL
                  value: https://prometheus-k8s-openshift-monitoring.apps.shift.nerc.mghpcc.org
                - name: OPENSHIFT_CLUSTER_NAME
                  value: nerc-openshift-prod
                - name: OPENSHIFT_SERVER_URL
                  value: https://api.shift.nerc.mghpcc.org:6443
                - name: OUTPUT_DIR
                  value: /data/xdmod_openshift_data/nerc_openshift_prod
                - name: XDMOD_RESOURCE
                  value: nerc_openshift_prod
                - name: OPENSHIFT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: xdmod-openshift-prod-secret
              command: ["/usr/bin/xdmod-openshift-reporting.sh"]
              volumeMounts:
                - name: vol-xdmod-init
                  mountPath: /mnt/xdmod_init
                - name: vol-var-log-xdmod
                  mountPath: /var/log/xdmod
                - name: vol-xdmod-openshift-data
                  mountPath: /data/xdmod_openshift_data
                - name: vol-xdmod-conf
                  mountPath: /etc/xdmod
          volumes:
            - name: vol-xdmod-init
              configMap:
                items:
                  - key: xdmod_init.json
                    path: xdmod_init.json
                name: cm-xdmod-init-json
            - name: vol-clouds-yaml
              emptyDir: {}
            - name: vol-xdmod-conf
              emptyDir: {}
            - name: vol-var-log-xdmod
              emptyDir: {}
            - name: vol-xdmod-openshift-data
              persistentVolumeClaim:
                claimName: pvc-xdmod-openshift-data
          restartPolicy: Never
