apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.3.34
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: pass
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: vol-mariadb
              mountPath: /var/lib/mysql
            - name: vol-mariadb-conf
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: vol-mariadb-conf
              mountPath: /etc/mysql/mariadb.cnf
              subPath: mariadb.cnf
            - name: vol-mariadb-conf
              mountPath: /etc/mysql/conf.d/mysqld_safe_syslog.cnf
              subPath: mysqld_safe_syslog.cnf
      volumes:
        - name: vol-mariadb
          persistentVolumeClaim:
            claimName: pvc-mariadb
        - name: vol-mariadb-conf
          configMap:
            name: cm-mariadb-conf
