apiVersion: batch/v1
kind: CronJob
metadata:
  name: xdmod-openshift-staging-job
spec:
  schedule: "0 1 */1 * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: xdmod-openshift-staging-job
              image: image-registry.openshift-image-registry.svc:5000/xdmod/moc-xdmod:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: xdmod-openshift-staging-secret
              env:
                - name: OPENSHIFT_PROMETHEUS_URL
                  value: https://prometheus-k8s-openshift-monitoring.apps.ocp-staging.massopen.cloud
                - name: OPENSHIFT_CLUSTER_NAME
                  value: nerc-openshift-staging
                - name: OPENSHIFT_SERVER_URL
                  value: https://api.ocp-staging.massopen.cloud:6443
                - name: OUTPUT_DIR
                  value: /data/xdmod_openshift_data/nerc_openshift_staging
                - name: XDMOD_RESOURCE
                  value: nerc_openshift_staging
              command: ["/usr/bin/xdmod-openshift-reporting.sh"]
              volumeMounts:
                - name: vol-xdmod-conf
                  mountPath: /etc/xdmod
                - name: vol-xdmod-src
                  mountPath: /usr/share/xdmod
                - name: vol-xdmod-init
                  mountPath: /mnt/xdmod_init
                - name: vol-var-log-xdmod
                  mountPath: /var/log/xdmod
                - name: vol-xdmod-openshift-data
                  mountPath: /data/xdmod_openshift_data
          volumes:
            - name: vol-xdmod-init
              configMap:
                items:
                  - key: xdmod_init.json
                    path: xdmod_init.json
                name: cm-xdmod-init-json
            - name: vol-xdmod-conf
              persistentVolumeClaim:
                claimName: pvc-xdmod-conf
            - name: vol-xdmod-src
              persistentVolumeClaim:
                claimName: pvc-xdmod-src
            - name: vol-var-log-xdmod
              emptyDir: {}
            - name: vol-xdmod-openshift-data
              persistentVolumeClaim:
                claimName: pvc-xdmod-openshift-data
          restartPolicy: Never
