commonLabels:
  app: xdmod
namespace: xdmod

resources:
  - pvc-mariadb.yaml
  - pvc-xdmod-conf.yaml
  - pvc-xdmod-src.yaml
  - pvc-xdmod-data.yaml
  - pvc-xdmod-openshift-data.yaml
  - pvc-clouds-yaml.yaml
  - pvc-httpd-conf.yaml
  - svc-mariadb.yaml
  - svc-xdmod.yaml
  - deployment-mariadb.yaml
  - deployment-xdmod.yaml
  - route-xdmod.yaml

configMapGenerator:
  - name: cm-xdmod-init-json
    files:
      - xdmod_init.json
  - name: cm-httpd-conf
    files:
      - httpd.conf
  - name: cm-my-conf
    files:
      - mariadb-conf/etc-mysql-my.cnf
  - name: cm-mariadb-conf
    files:
      - mariadb-conf/etc-mysql-mariadb.cnf
  - name: cm-mysql-safe-conf
    files:
      - mariadb-conf/etc-mysql-conf.d-mysqld_safe_syslog.cnf
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
