commonLabels:
  app: xdmod
namespace: xdmod

resources:
  - pvc-mariadb.yaml
  - pvc-xdmod-conf.yaml
  - pvc-xdmod-src.yaml
  - pvc-xdmod-data.yaml
  - svc-mariadb.yaml
  - svc-xdmod.yaml
  - deployment-mariadb.yaml
  #- deployment-xdmod.yaml
