kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: xdmod
namespace: xdmod

resources:
  - ns-xdmod.yaml
  - pvc-mariadb.yaml
  - pvc-xdmod-conf.yaml
  - pvc-xdmod-src.yaml
  - pvc-xdmod-data.yaml
  - pvc-xdmod-openstack-data.yaml
  - pvc-xdmod-openshift-data.yaml
  - pvc-clouds-yaml.yaml
  - pvc-httpd-conf.yaml
  - svc-mariadb.yaml
  - svc-mongo.yaml
  - svc-xdmod.yaml
  - deployment-mariadb.yaml
  - deployment-mongo.yaml
  - deployment-xdmod.yaml
  - route-xdmod.yaml
  - secret-xdmod-openshift-prod.yaml
  - cron-job-xdmod-ingestor.yaml
  - cron-job-xdmod-openshift-prod.yaml
  - cj-xdmod-openstack-shred.yaml

configMapGenerator:
  - name: cm-xdmod-init-json
    files:
      - xdmod_init.json
  - name: cm-httpd-conf
    files:
      - httpd.conf
  - name: cm-mariadb-conf
    files:
      - my.cnf=mariadb-conf/etc-mysql-my.cnf
      - mariadb.cnf=mariadb-conf/etc-mysql-mariadb.cnf
      - mysqld_safe_syslog.cnf=mariadb-conf/etc-mysql-conf.d-mysqld_safe_syslog.cnf
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
