apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: xdmod
spec:
  storageClassName: xdmod-mariadb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
