apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xdmod-openshift-prod-secret
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: xdmod-openshift-prod-secret
  data:
  - secretKey: token
    remoteRef:
      key: nerc/nerc-ocp-infra/xdmod/nerc-ocp-prod-xdmod-reader
      property: token
