apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xdmod-conf-pvc
  namespace: xdmod
spec:
  volumeName: xdmod-conf-pv
  storageClassName: xdmod-conf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
