kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: xdmod-staging
namespace: xdmod-staging

resources:
  - ../../xdmod-build
  - ../../kube-base

patchesStrategicMerge:
  - patches/cj-xdmod-ingestor.yaml
  - patches/cj-xdmod-openstack-shred.yaml
  - patches/deployment-xdmod.yaml
