apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bc-xdmod
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/CCI-MOC/xdmod-cntr.git
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7.9.2009
      dockerfilePath: Dockerfile.moc-xdmod
  output:
    to:
      kind: ImageStreamTag
      name: moc-xdmod:latest
  triggers:
    - type: ConfigChange
