apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bc-xdmod-dev
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/CCI-MOC/xdmod-cntr.git
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.moc-xdmod-dev
      from:
        kind: ImageStreamTag
        name: moc-xdmod:latest
  output:
    to:
      kind: ImageStreamTag
      name: moc-xdmod-dev:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: moc-xdmod:latest
